[tools]
actionlint = "latest"
biome = "latest"
bun = "latest"
cloudflared = "latest"
deno = "latest"
go = "latest"
helm = "latest"
java = "latest"
kubectl = "latest"
kustomize = "latest"
node = "latest"
pnpm = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
taplo = "latest"
terraform = "latest"
uv = "latest"
wrangler = "latest"

[tools."npm:@openai/codex"]
version = "latest"
minimum_release_age = "0s"
